"""intake store initial

Revision ID: 014212a07646
Revises: 
Create Date: 2026-09-13 00:09:05.405636
"""
from alembic import op
import sqlalchemy as sa


revision = '014212a07646'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_contacts',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('intake_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intake_contacts_created_on'), ['created_on'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intake_contacts_created_on'))

    op.drop_table('intake_contacts')
    # ### end Alembic commands ###
