"""case register initial

Revision ID: 97eb1794cbcb
Revises: 
Create Date: 2026-09-13 00:08:46.996428
"""
from alembic import op
import sqlalchemy as sa


revision = '97eb1794cbcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_code', sa.String(length=60), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('case_no', sa.String(length=24), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_actor_code'), ['actor_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_case_no'), ['case_no'], unique=False)

    op.create_table('case_counter',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_no', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_no', sa.String(length=24), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=160), nullable=False),
    sa.Column('zone', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('pin', sa.String(length=6), nullable=False),
    sa.Column('local_address', sa.Text(), nullable=False),
    sa.Column('amount_text', sa.String(length=160), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('accused_name', sa.String(length=120), nullable=True),
    sa.Column('accused_desig', sa.String(length=160), nullable=True),
    sa.Column('accused_code', sa.String(length=60), nullable=True),
    sa.Column('names_public', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('investigator_code', sa.String(length=24), nullable=True),
    sa.Column('penalty', sa.Text(), nullable=True),
    sa.Column('filed_on', sa.Date(), nullable=False),
    sa.Column('assigned_on', sa.Date(), nullable=True),
    sa.Column('decided_on', sa.Date(), nullable=True),
    sa.Column('has_followup', sa.Boolean(), nullable=False),
    sa.Column('overdue_flagged', sa.Boolean(), nullable=False),
    sa.CheckConstraint('length(pin) = 6', name='ck_pin_len'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_case_no'), ['case_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_cases_department'), ['department'], unique=False)
        batch_op.create_index('ix_cases_dept_status', ['department', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_filed_on'), ['filed_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_pin'), ['pin'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_zone'), ['zone'], unique=False)

    op.create_table('intake_throttle',
    sa.Column('bucket', sa.String(length=64), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('bucket', 'day'),
    sa.UniqueConstraint('bucket', 'day', name='uq_throttle')
    )
    op.create_table('ledger',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_no', sa.String(length=24), nullable=False),
    sa.Column('milestone', sa.String(length=120), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('entry_hash')
    )
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_case_no'), ['case_no'], unique=False)

    op.create_table('officials',
    sa.Column('employee_code', sa.String(length=60), nullable=False),
    sa.Column('department', sa.String(length=160), nullable=False),
    sa.Column('rank', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('employee_code')
    )
    with op.batch_alter_table('officials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_officials_department'), ['department'], unique=False)

    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_expires_at'), ['expires_at'], unique=False)

    op.create_table('used_totp',
    sa.Column('employee_code', sa.String(length=60), nullable=False),
    sa.Column('window', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('employee_code', 'window')
    )
    op.create_table('case_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_events_case_id'), ['case_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('stored_name', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=60), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('metadata_stripped', sa.Boolean(), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_case_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('case_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_events_case_id'))

    op.drop_table('case_events')
    op.drop_table('used_totp')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_expires_at'))

    op.drop_table('revoked_tokens')
    with op.batch_alter_table('officials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_officials_department'))

    op.drop_table('officials')
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_case_no'))

    op.drop_table('ledger')
    op.drop_table('intake_throttle')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_zone'))
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_pin'))
        batch_op.drop_index(batch_op.f('ix_cases_filed_on'))
        batch_op.drop_index(batch_op.f('ix_cases_district'))
        batch_op.drop_index('ix_cases_dept_status')
        batch_op.drop_index(batch_op.f('ix_cases_department'))
        batch_op.drop_index(batch_op.f('ix_cases_case_no'))

    op.drop_table('cases')
    op.drop_table('case_counter')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_case_no'))
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_code'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
